backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Stories"
    name: "stories"
    folder: "src/stories"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "story_id", name: "story_id", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - widget: "image"
        choose_url: true
        media_folder: "/static/img"
        media_library:
      config:
        multiple: true
      - widget: select
        label: "Age"
        name: "age"
        multiple: true
        create: true
        options:
          [
            "Toddlers (Ages 3-5)",
            "Young Children (Ages 6-8)",
            "Pre-Teens (Ages 9-12)",
          ]
      - widget: select
        label: "Theme"
        name: "theme"
        multiple: true
        create: true
        options:
          [
            "Kindness and Empathy",
            "Courage and Bravery",
            "Friendship and Cooperation",
            "Respect for Nature",
            "Family and Community",
            "Perseverance and Determination",
            "Honesty and Integrity",
            "Curiosity and Learning",
          ]
      - widget: select
        label: "Type"
        name: "type"
        multiple: true
        create: true
        options:
          [
            "Adventure Stories: Exciting narratives with challenges and discoveries.",
            "Everyday Life: Stories about daily life experiences and relatable situations.",
            "Mythology and Legends: Stories based on cultural myths and legends, adapted for children.",
            "Science and Exploration: Stories that include elements of science, exploration, and discovery",
          ]
      - widget: select
        label: "Character"
        name: "character"
        multiple: true
        create: true
        options:
          [
            "Animal Characters",
            "Human Characters",
            "Fantasy Creatures",
            "Robot Characters",
            "Alien Characters",
          ]
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
